--[[
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
]]

p, q, sum = 1, 1, 0
while q <= 4000000 do
	if q % 2 == 0 then sum = sum + q end

	p, q = q, p + q
end

print(sum)